# Generated by Django 3.0.5 on 2020-07-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200708_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='text',
            field=models.TextField(max_length=850, null=True),
        ),
    ]
