# Generated by Django 2.2 on 2020-07-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200708_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('speciality', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='doctors/')),
                ('details', models.TextField()),
                ('experience', models.TextField()),
                ('twiter', models.CharField(blank='True', max_length=150, null='True')),
                ('facebook', models.CharField(blank='True', max_length=150, null='True')),
                ('instagram', models.CharField(blank='True', max_length=150, null='True')),
            ],
        ),
        migrations.CreateModel(
            name='Expertize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
