# Generated by Django 2.2 on 2020-07-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_doctor_expertize'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='expertize',
            field=models.ManyToManyField(related_name='doctors', to='website.Expertize'),
        ),
    ]
