# Generated by Django 2.2 on 2020-07-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_doctor_expertize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='cover',
            field=models.ImageField(null=True, upload_to='service/'),
        ),
        migrations.AddField(
            model_name='service',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='service/'),
        ),
        migrations.AddField(
            model_name='service',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='service/'),
        ),
        migrations.AddField(
            model_name='service',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='service/'),
        ),
        migrations.AddField(
            model_name='service',
            name='items',
            field=models.ManyToManyField(to='website.Item'),
        ),
    ]
