# Generated by Django 2.2 on 2020-07-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20200720_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='doctors')),
                ('name', models.CharField(max_length=150)),
                ('speciality', models.CharField(max_length=200)),
                ('experience', models.TextField()),
                ('phone', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, null=True)),
            ],
        ),
    ]
