# Generated by Django 2.2 on 2020-07-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_equipment_experience_friendly_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('body', models.TextField()),
            ],
        ),
    ]
