# Generated by Django 2.2 on 2020-07-26 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dental_Technology',
        ),
        migrations.DeleteModel(
            name='Dentistry_Articles',
        ),
        migrations.DeleteModel(
            name='Healthy_Smiles',
        ),
        migrations.DeleteModel(
            name='Kids_Dental',
        ),
        migrations.DeleteModel(
            name='Oral_Health',
        ),
    ]
