# Generated by Django 2.2 on 2020-07-26 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20200726_1040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
