# Generated by Django 3.1.7 on 2021-02-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stage', models.CharField(max_length=300)),
                ('price', models.FloatField()),
            ],
        ),
    ]
